apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: facade-service
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: facade-service
            servicePort: 8080
