apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: facade-service
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: facade-service
            servicePort: 8080
